### ISSUE TITLE
References to modules should not omit eslint-config- prefix

### ISSUE THREAD

**Issue by felicio** [strvcom/eslint-config-javascript#27]
FOA great work team! This issue does not target any functional problem now but could prevent one in the future. Omitting `eslint-config-` prefix from scoped packages seems to be considered a bad practice and could lead to name collisions if you ever decide to release a package named 'javascript' under `@strv` scope. Not to mention that for a novice (like myself) it might be confusing when things are not called by their real names. Things, or shortcuts, I personally dislike in open source.

> The module name can also be customized, just note that when using scoped modules it is not possible to omit the eslint-config- prefix.
>
> [source](https://eslint.org/docs/developer-guide/shareable-configs#npm-scoped-modules)

If you find it of something worth changing I could be the one who will do it.

**Comment by robertrossmann** [comment]
Hi @felicio! Thanks for the suggestion. We at @strvcom are a well-organised team and if we ever decide to release a package named `@strv/javascript` (very unlikely) we will change the documentation in this repository accordingly so I do not see the need to change it right now.

As a second thought, the `eslint-config-` prefix' usage is determined by the package consumers, not by the package maintainers. As such, you are free to use the full package path in your config if you feel that is the proper way to do it.

If the ESLint team decides to drop support for this shortcut we will update our docs accordingly.
