### ISSUE TITLE
Add eslint-plugin-import-order-autofix

### ISSUE THREAD

**Issue by dannytce** [strvcom/eslint-config-javascript#30]
@robertrossmann  Any thoughts on this?

**Comment by honzasusek** [comment]
There's a reported issue with it that it removes lines (bad)
https://github.com/AlexJuarez/eslint-plugin-import-order-autofix/issues/3
But it seems to be fixed in this fork https://github.com/valentin-nemcev/eslint-plugin-import-order-autofix

**Comment by robertrossmann** [comment]
I am hesitant to include a plugin with such low usage, inactive maintainer (last commit Jan 17, 2017 😱) and a bug which removes code... Especially if adding it to the project takes about 2 lines of code.

**Comment by prichodko** [comment]
I agree with @robertrossmann here. However there is a rule in `eslint-plugin-import`, which seems to achieve same functionality - [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md).

Although it's not `auto-fixable` (which I don't mind anyway, because people will learn a good practice), it enforces consistency.

**Comment by robertrossmann** [comment]
I will close this for now in favour of `import/order`. I bet someone will eventually implement autofix for the `import/order` rule. ❤️

**Comment by prichodko** [comment]
Wanna send PR?

**Comment by robertrossmann** [comment]
@prichodko PR for what...?

**Comment by prichodko** [comment]
For enabling `import/order`...?

**Comment by robertrossmann** [comment]
FYI, `import/order` is now auto-fixable. 🎉 I'll consider enabling the rule in this ruleset (I like the idea, I think I just did not want to bother people to fix all the imports by hand), however in the meantime feel free to enable it on a per-project basis!

https://github.com/benmosher/eslint-plugin-import/pull/908
