### ISSUE TITLE
Configuration for rule "object-property-newline" is invalid:

### ISSUE THREAD

**Issue by ozluy** [strvcom/eslint-config-javascript#31]
getting this error on
### versions
```bash
"@strv/eslint-config-javascript": "^7.10.0",
"eslint": "^4.19.1",
```

### error detail
```js
Module build failed: Error: /path-project/node_modules/@strv/eslint-config-javascript/coding-styles/fixable.js:
	Configuration for rule "object-property-newline" is invalid:
	Value "[object Object]" should NOT have additional properties.

Referenced from: /path-project//node_modules/@strv/eslint-config-javascript/coding-styles/recommended.js
Referenced from: /path-project/.eslintrc
    at Array.forEach (<anonymous>)
    at Array.reduceRight (<anonymous>)
    at Array.reduceRight (<anonymous>)
```

**Comment by robertrossmann** [comment]
Hey @ozluy! This usually happens when ESLint or this ruleset does not get properly upgraded after installing new version.

I recommend dropping your _node_modules_ and optionally also _package-lock.json_ and installing all deps again. That should do the trick! 💪

**Comment by robertrossmann** [comment]
Hi @ozluy, did the above help fix the issue? If not, feel free to ping me on Slack! I'm closing this now as in the past this was always an issue with _node_modules_ being out of sync.
