### ISSUE TITLE
Upgrade eslint-plugin-flow to latest version

### ISSUE THREAD

**Issue by robertrossmann** [strvcom/eslint-config-javascript#34]
I could use a hand in upgrading [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype/releases) to the latest version (2.46.1). We are now using 2.39.1 .

@arnostpleskot Would you be willing to have a look at all the new rules and add them to this ruleset? 🙏 Ping me if you have time and I can provide further details. Thank you!

**Comment by arnostpleskot** [comment]
@robertrossmann I can take care of this, but as my initial commit was created just to make flow working with eslint, it would be better to check all rules by someone who has actual experience with flow on project.

@petyrek or @Zaggen can you look into this?

**Comment by robertrossmann** [comment]
I have upgraded the ruleset myself, to the best of my ability/knowledge. It will be available as `9.0.0` soon.
