### ISSUE TITLE
Add eslint-plugin-security

### ISSUE THREAD

**Issue by dannytce** [strvcom/eslint-config-javascript#41]
https://github.com/nodesecurity/eslint-plugin-security/

**Comment by robertrossmann** [comment]
Sooo... I was actually considering adding this plugin for quite some time. Today I decided to finally integrate it and realised that only 3 rules out of the whole plugin are currently usable:

- detect-unsafe-regex
- detect-eval-with-expression
- detect-non-literal-regexp

The rest is either so outdated that it no longer applies (detect-buffer-noassert - `noAssert` is deprecated and removed, detect-pseudoRandomBytes - this function is removed and is identical to that of crypto.randomBytes) or would cause too many false positives that it would actually hurt the developer experience than to provide actionable help (detect-object-injection - reports on every dynamic object access, detect-non-literal-fs-filename, detect-child-process, detect-possible-timing-attacks - lol, reports on every single comparison).

Given that the plugin is not being actively developed and the last officially supported ESLint version is ^2, I think it's too much of a maintenance risk to integrate this plugin for 3 somewhat usable rules. 😢


Here's the final patch if you are interested.

[0001-feat-add-eslint-plugin-security.patch.zip](https://github.com/strvcom/eslint-config-javascript/files/2527304/0001-feat-add-eslint-plugin-security.patch.zip)
