### ISSUE TITLE
Fix typescript environment README

### ISSUE THREAD

**Issue by bsunderhus** [strvcom/eslint-config-javascript#43]
Shouldn't it be:

```javascript
[
  '@strv/eslint-config-javascript/environments/nodejs/v10',
  '@strv/eslint-config-javascript/environments/nodejs/optional',
  '@strv/eslint-config-javascript/environments/typescript/recommended',
  '@strv/eslint-config-javascript/coding-styles/recommended',
]
```

instead of:

```javascript
[
  '@strv/javascript/environments/nodejs/v10',
  '@strv/javascript/environments/nodejs/optional',
  '@strv/javascript/environments/typescript/recommended',
  '@strv/javascript/coding-styles/recommended',
]
```

My eslint is not finding `@strv/javascript/`, but it does find `@strv/eslint-config-javascript/`

**Comment by robertrossmann** [comment]
Well, the `eslint-config` prefix should be optional starting with ESLint 4 or 5, I guess. Make sure you are running the latest version! Also make sure you are invoking the ESLint CLI directly, sometimes editor integrations bundle an older version which messes things up. 🤷‍♂️

**Comment by bsunderhus** [comment]
A global version of ESlint 3 being used by the editor! 🤦🏼‍♂️ Thx @robertrossmann!
